### ISSUE TITLE
[Minor bug] mentioning wunderbot then a command triggers "yes?" then the command response

### ISSUE THREAD

**Issue by littlemadhatter** [LBRYFoundation/lbry-wunderbot#305]
```
    if (msg.author !== bot.user && msg.isMentioned(bot.user)) {
      msg.channel.send('yes?'); //using a mention here can lead to looping
    } else {
    }
```
in bot/bot.js triggers:
![image](https://user-images.githubusercontent.com/31356843/81754363-de956b80-946a-11ea-8047-a7395443193f.png)

Alternatives: Allow if a valid command after a ping to respond with the command and not the "yes" (Kind of like a secondary prefix being the ping, I vote for this one), 
Check if the msg has a vaild command after the ping to not respond (Not suggestible), 
get rid of quirk (if you don't like quirks)

**Comment by Coolguy3289** [comment]
Mentions are broken right now, is up to be fixed next.

**Comment by Coolguy3289** [comment]
Fixed
